FROM gcr.io/datadoghq/agent:latest

# (Optional) Add custom configuration files
# COPY datadog.yaml /etc/datadog-agent/datadog.yaml
# COPY conf.d/nginx.d/conf.yaml /etc/datadog-agent/conf.d/nginx.d/conf.yaml